/**
 * Static mock data - replaces Prisma database queries
 * All data hardcoded from seed, no database connection needed.
 */

export const categories = [
  { id: 1, name: 'AI IDE & Editors', slug: 'ai-ide', description: 'AI-powered code editors and IDEs', icon: '💻', sortOrder: 1 },
  { id: 2, name: 'App Generators', slug: 'app-generators', description: 'Generate full apps from text descriptions', icon: '🚀', sortOrder: 2 },
  { id: 3, name: 'AI Code Assistants', slug: 'code-assistants', description: 'Inline code suggestions and chat', icon: '🤖', sortOrder: 3 },
  { id: 4, name: 'AI Agents', slug: 'ai-agents', description: 'Autonomous coding agents', icon: '🦾', sortOrder: 4 },
  { id: 5, name: 'UI Generators', slug: 'ui-generators', description: 'Generate UI components and designs', icon: '🎨', sortOrder: 5 },
]

export const tools = [
  {
    id: 1, name: 'Cursor', slug: 'cursor',
    description: 'The AI code editor built for vibe coding. Cursor is an AI code editor built on top of VS Code. It has AI chat, Composer for multi-file edits, Tab completion, and supports MCP. Free plan available, Pro at $20/mo.',
    shortDesc: 'AI-first code editor for vibe coding',
    websiteUrl: 'https://cursor.com', githubUrl: '', logoUrl: '',
    categoryId: 1, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'AI Editor,Vibe Coding,VS Code,IDE,MCP',
    features: 'AI Chat,Composer,Tab Completion,MCP Support,Codebase-wide context',
    source: 'manual', sourceUrl: 'https://cursor.com',
    stars: 28000, upvotes: 1500, viewCount: 120000,
    isFeatured: true, isActive: true, status: 'approved',
    createdAt: new Date('2024-01-01'), updatedAt: new Date(),
  },
  {
    id: 2, name: 'Bolt.new', slug: 'bolt-new',
    description: 'Bolt.new lets you build full-stack apps in your browser. You type what you want and the AI builds it. It uses StackBlitz WebContainers so your app runs right in the browser. Supports React, Next.js, Vue, and more.',
    shortDesc: 'Build full-stack apps in your browser with AI',
    websiteUrl: 'https://bolt.new', githubUrl: '', logoUrl: '',
    categoryId: 2, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'App Generator,Full-Stack,Vibe Coding,WebContainers',
    features: 'Full-stack generation,In-browser preview,StackBlitz integration,Multi-file editing',
    source: 'manual', sourceUrl: 'https://bolt.new',
    stars: 35000, upvotes: 2000, viewCount: 150000,
    isFeatured: true, isActive: true, status: 'approved',
    createdAt: new Date('2024-03-01'), updatedAt: new Date(),
  },
  {
    id: 3, name: 'Lovable', slug: 'lovable',
    description: 'Lovable is an AI app builder. You describe your app idea and it generates a full working app. It is good for MVPs and prototypes. You can iterate fast by chatting with the AI. Supports React and Tailwind.',
    shortDesc: 'AI app builder for rapid prototyping',
    websiteUrl: 'https://lovable.dev', githubUrl: '', logoUrl: '',
    categoryId: 2, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'App Generator,MVP,Prototype,Vibe Coding,React',
    features: 'Full app generation,Real-time preview,AI chat interface,One-click deploy',
    source: 'manual', sourceUrl: 'https://lovable.dev',
    stars: 22000, upvotes: 1200, viewCount: 90000,
    isFeatured: true, isActive: true, status: 'approved',
    createdAt: new Date('2024-05-01'), updatedAt: new Date(),
  },
  {
    id: 4, name: 'v0 by Vercel', slug: 'v0',
    description: 'v0 is a tool made by Vercel. You describe the UI you want and it generates React components. It uses shadcn/ui and Tailwind CSS. The output is production-ready code you can copy-paste into your project.',
    shortDesc: 'Generate React UI components from text descriptions',
    websiteUrl: 'https://v0.dev', githubUrl: '', logoUrl: '',
    categoryId: 5, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'UI Generator,React,Tailwind,shadcn/ui,Vibe Coding',
    features: 'UI generation,React components,Tailwind CSS,shadcn/ui,Copy-paste ready',
    source: 'manual', sourceUrl: 'https://v0.dev',
    stars: 18000, upvotes: 1000, viewCount: 80000,
    isFeatured: true, isActive: true, status: 'approved',
    createdAt: new Date('2024-02-01'), updatedAt: new Date(),
  },
  {
    id: 5, name: 'Claude Code', slug: 'claude-code',
    description: 'Claude Code is Anthropic\'s agentic coding tool. It works in the terminal. You can give it complex tasks and it will plan and execute. It can search code, edit files, run tests, and fix bugs. Best for complex development tasks.',
    shortDesc: 'Anthropic\'s agentic coding tool for the terminal',
    websiteUrl: 'https://claude.ai', githubUrl: '', logoUrl: '',
    categoryId: 1, pricingType: 'PAID', isOpenSource: false,
    tags: 'AI Editor,Terminal,Agent,Coding Agent,Anthropic',
    features: 'Terminal-based,Agentic workflow,Code search,Multi-file editing,Test running',
    source: 'manual', sourceUrl: 'https://claude.ai',
    stars: 15000, upvotes: 900, viewCount: 70000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2024-06-01'), updatedAt: new Date(),
  },
  {
    id: 6, name: 'Windsurf', slug: 'windsurf',
    description: 'Windsurf is an AI-powered IDE by Codeium. It has a feature called Cascade for multi-file edits. It understands your entire codebase context. Good for large projects and enterprise teams.',
    shortDesc: 'AI IDE with Cascade multi-file editing',
    websiteUrl: 'https://codeium.com/windsurf', githubUrl: '', logoUrl: '',
    categoryId: 1, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'AI Editor,IDE,Cascade,Codeium,Vibe Coding',
    features: 'AI Flow,Cascade multi-file edits,Codebase context,Enterprise features',
    source: 'manual', sourceUrl: 'https://codeium.com/windsurf',
    stars: 12000, upvotes: 800, viewCount: 60000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2024-07-01'), updatedAt: new Date(),
  },
  {
    id: 7, name: 'Replit Agent', slug: 'replit-agent',
    description: 'Replit Agent builds full apps from natural language. It runs on Replit\'s cloud platform so you can deploy instantly. It can build web apps, APIs, and more. Good for learning and quick MVPs.',
    shortDesc: 'Build and deploy apps from natural language on Replit',
    websiteUrl: 'https://replit.com', githubUrl: '', logoUrl: '',
    categoryId: 2, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'App Generator,Cloud,Deploy,Vibe Coding,Replit',
    features: 'Natural language to app,Instant deployment,Cloud platform,Collaboration',
    source: 'manual', sourceUrl: 'https://replit.com',
    stars: 10000, upvotes: 700, viewCount: 50000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2024-08-01'), updatedAt: new Date(),
  },
  {
    id: 8, name: 'GitHub Copilot', slug: 'github-copilot',
    description: 'GitHub Copilot is the most popular AI coding assistant. It gives you code suggestions as you type. It works in VS Code, JetBrains, and more. It also has chat and agent features for more complex tasks.',
    shortDesc: 'The original AI pair programmer by GitHub',
    websiteUrl: 'https://github.com/features/copilot', githubUrl: '', logoUrl: '',
    categoryId: 3, pricingType: 'PAID', isOpenSource: false,
    tags: 'Code Assistant,Completion,Chat,Agent,GitHub',
    features: 'Code completion,Copilot Chat,Agent mode,Multi-IDE support,PR descriptions',
    source: 'manual', sourceUrl: 'https://github.com/features/copilot',
    stars: 50000, upvotes: 5000, viewCount: 300000,
    isFeatured: true, isActive: true, status: 'approved',
    createdAt: new Date('2023-06-01'), updatedAt: new Date(),
  },
  {
    id: 9, name: 'Devin', slug: 'devin',
    description: 'Devin is an AI software engineer by Cognition AI. It can plan, code, debug, and deploy on its own. It is designed for autonomous software development. Good for complex engineering tasks.',
    shortDesc: 'Autonomous AI software engineer by Cognition AI',
    websiteUrl: 'https://cognition.ai', githubUrl: '', logoUrl: '',
    categoryId: 4, pricingType: 'PAID', isOpenSource: false,
    tags: 'AI Agent,Autonomous,Software Engineer,Cognition',
    features: 'Autonomous coding,Task planning,Debugging,Deployment,Shell access',
    source: 'manual', sourceUrl: 'https://cognition.ai',
    stars: 8000, upvotes: 500, viewCount: 40000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2024-09-01'), updatedAt: new Date(),
  },
  {
    id: 10, name: 'Aider', slug: 'aider',
    description: 'Aider is an AI pair programming tool for the terminal. It is open source and works with many LLMs. You can chat with the AI about your code and it will make edits. It works with Git for easy tracking.',
    shortDesc: 'Open source AI pair programming in your terminal',
    websiteUrl: 'https://aider.chat', githubUrl: 'https://github.com/paul-gauthier/aider', logoUrl: '',
    categoryId: 3, pricingType: 'FREE', isOpenSource: true,
    tags: 'Open Source,Terminal,AI Pair Programming,Git,LLM',
    features: 'Terminal-based,Open source,Multi-LLM support,Git integration,Map-reduce editing',
    source: 'github', sourceUrl: 'https://github.com/paul-gauthier/aider',
    stars: 25000, upvotes: 1300, viewCount: 100000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2023-08-01'), updatedAt: new Date(),
  },
  {
    id: 11, name: 'Continue', slug: 'continue',
    description: 'Continue is an open source AI code assistant. It is an IDE extension that works with VS Code and JetBrains. You can use your own API keys and models. Supports chat, autocomplete, and custom slash commands.',
    shortDesc: 'Open source AI code assistant for VS Code and JetBrains',
    websiteUrl: 'https://continue.dev', githubUrl: 'https://github.com/continuedev/continue', logoUrl: '',
    categoryId: 3, pricingType: 'FREE', isOpenSource: true,
    tags: 'Open Source,IDE Extension,VS Code,JetBrains,LLM',
    features: 'IDE extension,Open source,Custom models,Slash commands,Autocomplete',
    source: 'github', sourceUrl: 'https://github.com/continuedev/continue',
    stars: 20000, upvotes: 1000, viewCount: 90000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2023-10-01'), updatedAt: new Date(),
  },
  {
    id: 12, name: 'Tabnine', slug: 'tabnine',
    description: 'Tabnine is an AI code completion tool. It is focused on privacy and enterprise security. It can run on your own infrastructure. Supports many languages and IDEs. Good for companies with strict security requirements.',
    shortDesc: 'Privacy-focused AI code completion for enterprise',
    websiteUrl: 'https://tabnine.com', githubUrl: '', logoUrl: '',
    categoryId: 3, pricingType: 'FREEMIUM', isOpenSource: false,
    tags: 'Code Completion,Privacy,Enterprise,Self-hosted',
    features: 'Code completion,Self-hosted option,Privacy focused,Multi-language,Enterprise',
    source: 'manual', sourceUrl: 'https://tabnine.com',
    stars: 10000, upvotes: 600, viewCount: 50000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2022-01-01'), updatedAt: new Date(),
  },
  {
    id: 13, name: 'Codeium', slug: 'codeium',
    description: 'Codeium is a free AI code completion and chat tool. It supports 70+ languages and 40+ editors. It has a generous free tier that is popular with indie developers and students.',
    shortDesc: 'Free AI code completion and chat for 70+ languages',
    websiteUrl: 'https://codeium.com', githubUrl: '', logoUrl: '',
    categoryId: 3, pricingType: 'FREE', isOpenSource: false,
    tags: 'Code Completion,Chat,Free,Multi-language',
    features: 'Code completion,AI chat,70+ languages,40+ editors,Free tier',
    source: 'manual', sourceUrl: 'https://codeium.com',
    stars: 15000, upvotes: 900, viewCount: 70000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2023-01-01'), updatedAt: new Date(),
  },
  {
    id: 14, name: 'Amazon Q Developer', slug: 'amazon-q',
    description: 'Amazon Q Developer is AWS\'s AI coding assistant. It helps with AWS-specific development. It understands AWS services deeply. Good for teams building on AWS infrastructure.',
    shortDesc: 'AWS AI coding assistant for cloud-native development',
    websiteUrl: 'https://aws.amazon.com/q/developer/', githubUrl: '', logoUrl: '',
    categoryId: 3, pricingType: 'FREE', isOpenSource: false,
    tags: 'Code Assistant,AWS,Cloud,Enterprise',
    features: 'AWS integration,Code completion,Security scanning,Cloud-native,Free tier',
    source: 'manual', sourceUrl: 'https://aws.amazon.com/q/developer/',
    stars: 5000, upvotes: 300, viewCount: 30000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2024-04-01'), updatedAt: new Date(),
  },
  {
    id: 15, name: 'Sourcegraph Cody', slug: 'sourcegraph-cody',
    description: 'Cody is a free AI code assistant by Sourcegraph. It understands your entire codebase. It can answer questions about your code, fix bugs, and write new features. Good for large codebases.',
    shortDesc: 'AI assistant that understands your entire codebase',
    websiteUrl: 'https://sourcegraph.com/cody', githubUrl: 'https://github.com/sourcegraph/cody', logoUrl: '',
    categoryId: 3, pricingType: 'FREE', isOpenSource: true,
    tags: 'Open Source,Codebase Context,Free,Code Search',
    features: 'Codebase context,Free tier,Code search,AI chat,Open source',
    source: 'github', sourceUrl: 'https://github.com/sourcegraph/cody',
    stars: 12000, upvotes: 700, viewCount: 60000,
    isFeatured: false, isActive: true, status: 'approved',
    createdAt: new Date('2023-11-01'), updatedAt: new Date(),
  },
]

// News items (empty for now)
export const news: any[] = []
